
import { MenuItem, NavLink, Testimonial } from './types';
import { ChefHat, Leaf, Star, Flame } from 'lucide-react';

export const NAV_LINKS: NavLink[] = [
  { label: 'Menu', path: '/menu' },
  { label: 'Trays', path: '/party-trays' },
  { label: 'Catering', path: '/catering' },
  { label: 'Gallery', path: '/gallery' },
  { label: 'About', path: '/about' },
  { label: 'Contact', path: '/contact' },
];

export const MENU_CATEGORIES = [
  'All',
  'Lunch Specials',
  'Vegetarian Appetizers',
  'Non-Veg Appetizers',
  'Tandoor (Clay Oven)',
  'Vegetarian Entrees',
  'Chicken Entrees',
  'Lamb & Goat Entrees',
  'Seafood Entrees',
  'Biryani & Rice',
  'Breads',
  'Sides',
  'Desserts',
  'Beverages'
];

export const MENU_ITEMS: MenuItem[] = [
  // --- Lunch Specials ---
  {
    id: 'ls1',
    name: 'Malai Kofta Lunch Special',
    description: 'Mix Vegetable and Cheese Dumpling in A Rich Saffron Sauce. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$16.00',
    category: 'Lunch Specials',
    isVegetarian: true,
  },
  {
    id: 'ls2',
    name: 'Chicken Vindaloo Lunch Special',
    description: 'Morsels of Chicken Cooked in a Chilli, Vinegar. Garlic Gravy not for faint - hearted. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$17.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls3',
    name: 'Chicken Tikka Masala Lunch Special',
    description: 'Chicken cooked in mildly spiced tomato sauce with peppers, onions. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$17.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls4',
    name: 'Rara Bhuna Goat Lunch Special',
    description: 'Goat meat stir-cooked in a semi dry brown sauce & caramelized onion. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$18.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls5',
    name: 'Goan Fish Curry Lunch Special',
    description: 'Fish Curry Cooked With Coconut Milk & Indian Herbs & Spices. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$18.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls6',
    name: 'Chicken Makhani (Butter Chicken) Lunch',
    description: 'Chicken Pieces Roasted In The Clay Oven And Tossed In A Creamy Tomato Sauce. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$17.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls7',
    name: 'Chicken Korma Lunch Special',
    description: 'Tender pieces of chicken cooked in a creamy saffron sauce with cardamom. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$17.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls8',
    name: 'Baingan Bharta Lunch',
    description: 'Charcoal Grilled Eggplant Cooked with Onions, Tomatoes, Ginger. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$16.00',
    category: 'Lunch Specials',
    isVegetarian: true,
  },
  {
    id: 'ls9',
    name: 'Aloo Gobi Lunch Special',
    description: 'Florets of Cauliflower & Potato Cubes Sauteed With Ginger, Turmeric & Spices. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$16.00',
    category: 'Lunch Specials',
    isVegetarian: true,
  },
  {
    id: 'ls10',
    name: 'Chicken Methi Lunch Special',
    description: 'Chicken curry cooked with fresh fenugreek. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$17.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls11',
    name: 'Lamb Rogan Josh Lunch Special',
    description: 'Braised lamb, brown onion, Kashmiri spices. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$18.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls12',
    name: 'Goat Vindaloo Lunch Special',
    description: 'Goat Meat Cooked in a Chilli, Vinegar. Garlic Gravy not for faint - hearted. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$18.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls13',
    name: 'Shrimp Bhuna Lunch Special',
    description: 'Shrimps cooked in a wok with garlic, freshly ground spices, peppers & onions. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$18.00',
    category: 'Lunch Specials',
  },
  {
    id: 'ls14',
    name: 'Palak Paneer Lunch Special',
    description: 'Cottage Cheese Sauteed in Spinach. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$16.00',
    category: 'Lunch Specials',
    isVegetarian: true,
  },
  {
    id: 'ls15',
    name: 'Paneer Makhani Lunch',
    description: 'Fresh Cottage Cheese Cooked In Creamy Tomato Sauce. Served With Choice Of One Starter, Basmati Rice, Dal Of The Day, Salad & Dessert Of The Day.',
    price: '$16.00',
    category: 'Lunch Specials',
    isVegetarian: true,
  },

  // --- Vegetarian Appetizers ---
  {
    id: 'va1',
    name: 'Vegetable Samosa',
    description: 'Vegetarian. Crispy turnovers, seasoned potatoes, green peas',
    price: '$9.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'va2',
    name: 'Lasuni Gobi',
    description: 'Spicy. Vegetarian. Cauliflower florets tossed in a soy burnt garlic sauce',
    price: '$14.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'va3',
    name: 'Palak Chaat',
    description: 'Vegetarian. Crispy spinach, pomegranate, yogurt, tamarind chutney, mint chutney, chopped tomato, and onions',
    price: '$13.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'va4',
    name: 'Samosa Chaat',
    description: 'Vegetarian. Crispy turnovers, seasoned potatoes, green peas',
    price: '$13.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
  },
  {
    id: 'va5',
    name: 'Paneer Tikka',
    description: 'Vegetarian. Cottage cheese marinated with yogurt, cream, turmeric, and Indian spices',
    price: '$15.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'va6',
    name: 'Truffle Grilled Mushrooms',
    description: 'Signature Chargrilled Mushrooms With Truffle Oil',
    price: '$16.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'va7',
    name: 'Dahi Aloo Papri',
    description: 'A Spiced Mixture Of Wheat Crisps, Potatoes, Chickpeas, Yogurt, Tamarind & Mint Chutney',
    price: '$13.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
  },
  {
    id: 'va8',
    name: 'Fig Naan With Spiced Eggplant',
    description: 'Fluffy naan served with spiced eggplant mash and figs',
    price: '$16.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'va9',
    name: 'Aloo Tikki With Pindi Cholley',
    description: 'Potato Patties With Smokey Chickpeas May Contain Nuts',
    price: '$14.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
  },
  {
    id: 'va10',
    name: 'Honey Chili Lotus',
    description: 'Lotus Root, Spring Onion, Honey, Garlic, Dry Chili Paste',
    price: '$14.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'va11',
    name: 'Beetroot Tikki',
    description: 'Vegetarian. Goat cheese, beets, potato crisps',
    price: '$15.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'va12',
    name: 'Pickled Mushrooms',
    description: 'Vegetarian. Spicy. Chargrilled mushrooms marinated in a robust pickle seasoning',
    price: '$16.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'va13',
    name: 'Dahi Ke Kabab',
    description: 'Crispy golden patty of spiced hung curd paneer and herbs with creamy center, served with mint chutney',
    price: '$15.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
  },
  {
    id: 'va14',
    name: 'Tandoori Broccoli',
    description: 'BROCCOLI CROWNS MARINATED WITH YOGURT CREAM TURMERIC & SPICES',
    price: '$14.00',
    category: 'Vegetarian Appetizers',
    isVegetarian: true,
    isGlutenFree: true,
  },

  // --- Non-Veg Appetizers ---
  {
    id: 'nva1',
    name: 'Aslam Butter Chicken Tikka',
    description: 'A Signature Of Old Delhi, Chicken Tikka Tossed With Smokey Butter & Cream',
    price: '$16.00',
    category: 'Non-Veg Appetizers',
    isChefSpecial: true,
    isGlutenFree: true,
  },
  {
    id: 'nva2',
    name: 'Chili Garlic Chicken',
    description: 'Spicy Fried Chicken Tossed In Tongue Teasing Blend Of Green Onion, Ginger And Garlic',
    price: '$17.00',
    category: 'Non-Veg Appetizers',
  },
  {
    id: 'nva3',
    name: 'Kabab Trio',
    description: 'A tasting trio of hariyali kabab, malai kabab and chicken tikka',
    price: '$15.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva4',
    name: 'Truffle Bhuna Chicken Bao Buns(3)',
    description: 'Soft bao buns filled with tender chicken in a rich bhuna masala, kissed with truffle oil, topped with cilantro and tamarind chutney.',
    price: '$15.00',
    category: 'Non-Veg Appetizers',
  },
  {
    id: 'nva5',
    name: 'Malai Fish Tikka',
    description: 'Cubes Of Salmon Marinated With Yogurt, Ginger, Garlic & Spices, Cooked In Our Clay Oven',
    price: '$16.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva6',
    name: 'Afghani Chicken Kabab',
    description: 'Boneless morsels of chicken marinated in ginger, garlic and cardamom',
    price: '$16.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva7',
    name: 'Mango Tulsi Prawns',
    description: 'Tandoori grilled shrimps with fresh basil and mango puree',
    price: '$17.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva8',
    name: 'Achari Fish Tikka',
    description: 'Cubes Of Salmon Marinated In Yogurt And Spices With A Subtle Flavor Of Pickle',
    price: '$17.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva9',
    name: 'Masala Calamari',
    description: 'Premium-quality calamari fried to golden perfection, then tossed with onions and peppers in a bold, spicy tomato masala. A Jalwa favorite...',
    price: '$15.00',
    category: 'Non-Veg Appetizers',
  },
  {
    id: 'nva10',
    name: 'Saffron Butter Garlic Crab',
    description: 'Fresh blue crab simmered in rich saffron-infused butter and garlic, finished with cracked black pepper for a fragrant, velvety indulgence.',
    price: '$15.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'nva11',
    name: 'Sukha Goat',
    description: 'Tender pieces of baby goat slow-cooked with aromatic spices, herbs, and caramelized onions. A flavorful dry appetizer from Jalwa, bursting...',
    price: '$22.00',
    category: 'Non-Veg Appetizers',
    isGlutenFree: true,
  },
  {
    id: 'nva12',
    name: 'Chicken Tandoori Momo',
    description: 'Smoky Grilled Dumplings Stuffed With Spiced & Chicken Marinated In Tandoori Flavours Served With A Zesty Sauces',
    price: '$15.00',
    category: 'Non-Veg Appetizers',
  },

  // --- Tandoor (Clay Oven) ---
  {
    id: 'tan1',
    name: 'Tandoori Shrimp',
    description: 'Jumbo shrimps marinated in a traditional style with a dash of saffron; cooked in tandoor',
    price: '$29.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan2',
    name: 'Tandoori Chicken',
    description: '1/2 chicken marinated with yogurt and spices and cooked in a tandoor; the tastiest way to barbecue chicken',
    price: '$25.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan3',
    name: 'Mahi Tandoori',
    description: 'Fillets of salmon spiced and grilled in the clay oven',
    price: '$29.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan4',
    name: 'Lamb Seekh Kabab',
    description: 'Skewered ground lamb grilled, tempered with chopped onion, ginger, garlic, saffron and spices',
    price: '$28.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan5',
    name: 'Murgh Malai Kabab',
    description: 'Boneless chicken breast seasoned with an array of herbs, spices, ginger and garlic',
    price: '$27.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan6',
    name: 'Jalwa Lamb Chops',
    description: 'Lamb chops marinated in fresh ginger and garlic cooked to your taste, served with grilled vegetables',
    price: '$34.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'tan7',
    name: 'Jalwa Tandoori Mix Grill',
    description: 'A Sampling of Hariyali Kabab, Malai Kabab, Chicken Tikka Kabab, Lamb Barrah Kabab & Lamb Seekh Kabab',
    price: '$34.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'tan8',
    name: 'Achari Chicken Tikka',
    description: 'Boneless morsels of chicken, marinated in a pickle seasoning',
    price: '$27.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan9',
    name: 'Barrah Kabab',
    description: 'Boneless lamb marinated in yogurt, ginger, garlic and spices',
    price: '$28.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan10',
    name: 'Mal Mal Kabab',
    description: 'Skewered ground chicken grilled, tempered with chopped onion, ginger, garlic, saffron and spices',
    price: '$27.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan11',
    name: 'Tandoori Indian Pomfret',
    description: 'Succulent pomfret fish marinated in aromatic spices, cooked to perfection in a traditional tandoori clay oven',
    price: '$25.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'tan12',
    name: 'Mango Habanero Chicken Curry',
    description: 'Boneless Pieces Of Chicken Cooked In House Special Habanero Sauce Infused With Mango',
    price: '$25.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'tan13',
    name: 'Grilled Vegetables',
    description: 'The best pick of greens, onions, bell peppers, Cottage cheese, broccoli and cauliflower served hot with pineapple',
    price: '$24.00',
    category: 'Tandoor (Clay Oven)',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'tan14',
    name: 'Sharabi Kabab',
    description: 'Boneless morsels of chicken, marinated in yogurt and spices, our version of chicken tikka',
    price: '$26.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan15',
    name: 'Hariyali Chicken Tikka',
    description: 'Boneless pieces of chicken marinated in mint and coriander',
    price: '$27.00',
    category: 'Tandoor (Clay Oven)',
    isGlutenFree: true,
  },
  {
    id: 'tan16',
    name: 'Pudina Paneer Tikka',
    description: 'An exotic mint-flavored homemade Cottage cheese kabab for vegetarians',
    price: '$25.00',
    category: 'Tandoor (Clay Oven)',
    isVegetarian: true,
    isGlutenFree: true,
  },

  // --- Vegetarian Entrees ---
  {
    id: 've1',
    name: 'Palak Paneer',
    description: 'Vegetarian. Fresh creamed spinach cooked with cubes of homemade cottage cheese. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've2',
    name: 'Paneer Tikka Masala',
    description: 'Vegetarian. Cottage cheese cooked in mildly spiced tomato onion gravy with peppers, onions, and cilantro. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've3',
    name: 'Aloo Gobi Masala Dum (Vegan)',
    description: 'Vegetarian. Florets of cauliflower and potato cubes sauteed with ginger, turmeric, and spices. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've4',
    name: 'Dal Makhani',
    description: 'Vegetarian. A harmonious combination of black lentils cooked over a slow fire. A dish from the famous itc Bukhara at the Maurya. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've5',
    name: 'Malai Kofte',
    description: 'Vegetarian. Vegetable and cheese dumplings in a rich cashew sauce. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
  },
  {
    id: 've6',
    name: 'Dal Jalwa (Yellow)',
    description: 'A smooth yellow lentil delicacy from the kitchens of the North-West frontier. Vegan. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've7',
    name: 'Mirchi Baingan Ka Salan (Vegan)',
    description: 'Spicy. Vegetarian. Long hot chilis, baby eggplant, ginger, garlic, and mustard seeds in a savory semi-gravy. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've8',
    name: 'Baingan Bharta (Vegan)',
    description: 'Vegetarian. Charcoal grilled buttery eggplant, cooked with onions, tomatoes, ginger, and cilantro. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've9',
    name: 'Pindi Cholley (Vegan)',
    description: 'Vegetarian. Pindi chole is a smokier version of chana masala. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've10',
    name: 'Vegetable Korma',
    description: 'Vegetarian. Fresh mixed vegetables cooked in a silky cashew korma sauce. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've11',
    name: 'Bhindi Masala (Vegan)',
    description: 'Vegetarian. Fresh okra tossed with onions, spices and sprinkled with fresh cilantro. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've12',
    name: 'Dal Palak',
    description: 'A Harmonious Combination Of Yellow Lentils Simmered Overnight & Fresh Spinach. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've13',
    name: 'Dal Frontier',
    description: 'A Combination Of Black And Yellow Lentils Simmered Overnight And Tempered With Ginger, Garlic And Cumin Seeds. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've14',
    name: 'Veg Kolhapuri',
    description: 'Mixed vegetables cooked in a thick, spicy gravy with traditional Kolhapuri spices, featuring a blend of onion, tomato, mustard seeds. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've15',
    name: 'Kadai Paneer',
    description: 'A semi-dry & colorful preparation of home-made cottage cheese cooked in a wok with bell pepper & tomatoes. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've16',
    name: 'Paneer Dilruba',
    description: 'Vegetarian. Cubed cottage cheese cooked in creamy tomato gravy. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 've17',
    name: 'Subzi Ki Tarkari (Vegan)',
    description: 'A mélange of fresh green vegetables cooked with onion, tomatoes, peppers, paneer & fresh ground spices. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've18',
    name: 'Bhindi Jalwa (Crispy Okra)',
    description: 'Vegetarian. Fresh crispy okra tossed with masalas-almost like okra chips. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 've19',
    name: 'Gobi Taka Tin (Vegan)',
    description: 'Vegetarian. Florets of cauliflower cooked in an Indian wok tossed with peppers, onions, and tomatoes. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've20',
    name: 'Anjeer Kofte',
    description: 'Fig And Cheese Dumplings In A Rich Saffron Creamy Sauce. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
  },
  {
    id: 've21',
    name: 'Chana Masala (Vegan)',
    description: 'Vegetarian. Chickpeas cooked with onions, garlic, ginger, and spices. Served with basmati rice',
    price: '$23.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 've22',
    name: 'Methi Paneer Malai Toast',
    description: 'Vegetarian. A double layer of mint cottage cheese triangles baked and plated in a creamy fenugreek and cardamon gravy. Served with basmati rice',
    price: '$24.00',
    category: 'Vegetarian Entrees',
    isVegetarian: true,
  },

  // --- Chicken Entrees ---
  {
    id: 'ce1',
    name: 'Chicken Tikka Masala',
    description: 'The most popular dish! Chicken cooked in mildly spiced tomato sauce with peppers, onions, and cilantro. Served with basmati rice',
    price: '$26.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce2',
    name: 'Shahi Murgh Korma',
    description: 'Tender pieces of chicken cooked in a creamy cashew sauce with cardamom. Served with basmati rice',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce3',
    name: 'Chicken Vindaloo',
    description: 'Medium. Chili, vinegar, and garlic, not for the faint-hearted. Served with basmati rice',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce4',
    name: 'Pandara Road Wala Butter Chicken',
    description: 'Chicken on the bone cooked in a creamy spicy tomato gravy. The way it is prepared in Delhi, India. Served with basmati rice',
    price: '$30.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'ce5',
    name: 'Goan Chicken Curry',
    description: 'Chicken Curry Cooked With Traditional Goan Spices & Fresh Coconut',
    price: '$27.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce6',
    name: 'Chicken Saagwala',
    description: 'Boneless pieces of chicken sauteed with sweet tender spinach and enhanced with aromatic spices. Served with basmati rice',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce7',
    name: 'Chicken Chettinad',
    description: 'A spicy South Indian curry with tender chicken, Chettinad spices, black pepper, and curry leaves',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce8',
    name: 'Kadai Chicken',
    description: 'Chicken sauteed in an Indian wok tossed with peppers, onions, and Indian herbs and spices. Served with basmati rice',
    price: '$24.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce9',
    name: 'Chicken Methi',
    description: 'Chicken curry cooked with fresh fenugreek. Served with basmati rice',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce10',
    name: 'Chicken Makhani',
    description: 'Chicken pieces roasted in the clay oven and tossed in a creamy tomato sauce. Unquestionably the most versatile delicacy in the north of India.',
    price: '$27.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },
  {
    id: 'ce11',
    name: 'Tariwala Kukkad',
    description: 'Chicken cooked in an onion, tomato, and yogurt-based sauce, flavored with ginger, garlic, chills, and a variety of spices our homestyle way.',
    price: '$25.00',
    category: 'Chicken Entrees',
    isGlutenFree: true,
  },

  // --- Lamb & Goat Entrées ---
  {
    id: 'lge1',
    name: 'Lamb Rogan Josh',
    description: 'Braised lamb, brown onion, Kashmiri spices. Served with basmati rice',
    price: '$28.00',
    category: 'Lamb & Goat Entrees',
    isGlutenFree: true,
  },
  {
    id: 'lge2',
    name: 'Jalwa Lamb Korma',
    description: 'Tender lamb cubes cooked with a special silky korma sauce. Served with basmati rice',
    price: '$27.00',
    category: 'Lamb & Goat Entrees',
    isGlutenFree: true,
  },
  {
    id: 'lge3',
    name: 'Lamb Tikka Masala',
    description: 'Tender lamb cubes cooked in mildly spiced tomato onion gravy with peppers, onions, and cilantro. Served with basmati rice',
    price: '$27.00',
    category: 'Lamb & Goat Entrees',
    isGlutenFree: true,
  },
  {
    id: 'lge4',
    name: 'Classic Goat Curry',
    description: 'Goat cooked in an onion, tomato, and yogurt-based sauce, flavored with ginger, garlic, and chilis. Served with basmati rice',
    price: '$28.00',
    category: 'Lamb & Goat Entrees',
    isGlutenFree: true,
    isChefSpecial: true,
  },
  {
    id: 'lge5',
    name: 'Rara Bhuna Goat',
    description: 'Goat meat stir-cooked in a semi-dry brown sauce and caramelized onion. Served with basmati rice',
    price: '$27.00',
    category: 'Lamb & Goat Entrees',
    isGlutenFree: true,
  },

  // --- Seafood Entrées ---
  {
    id: 'se1',
    name: 'Goan Shrimp Curry',
    description: 'A traditional Goan shrimp curry cooked to perfection with mustard seeds, tamarind, and fresh coconut milk',
    price: '$28.00',
    category: 'Seafood Entrees',
    isGlutenFree: true,
  },
  {
    id: 'se2',
    name: 'Methi Machli',
    description: 'Salmon Cooked In A Light Curry Gravy With Fresh Fenugreek',
    price: '$28.00',
    category: 'Seafood Entrees',
    isGlutenFree: true,
  },
  {
    id: 'se3',
    name: 'Garlic Shrimp Bhuna',
    description: 'Shrimps cooked in a wok with garlic, freshly ground spices, peppers & onions',
    price: '$28.00',
    category: 'Seafood Entrees',
    isGlutenFree: true,
  },
  {
    id: 'se4',
    name: 'Goan Fish Curry',
    description: 'A Goan specialty fish curry cooked with coconut milk & Indian herbs & spices',
    price: '$28.00',
    category: 'Seafood Entrees',
    isGlutenFree: true,
    isChefSpecial: true,
  },

  // --- Biryani & Rice ---
  {
    id: 'br1',
    name: 'Dum Pukht Chicken Biryani',
    description: 'Aromatic basmati rice cooked with chicken. (Served with raita)',
    price: '$25.00',
    category: 'Biryani & Rice',
    isGlutenFree: true,
  },
  {
    id: 'br2',
    name: 'Dum Pukht Lamb Biryani',
    description: 'Aromatic basmati rice cooked with lamb. (Served with raita)',
    price: '$27.00',
    category: 'Biryani & Rice',
    isGlutenFree: true,
  },
  {
    id: 'br3',
    name: 'Dum Pukht Goat Biryani',
    description: 'Aromatic basmati rice cooked with a goat. (Served with raita)',
    price: '$26.00',
    category: 'Biryani & Rice',
    isGlutenFree: true,
  },
  {
    id: 'br4',
    name: 'Basmati Rice',
    description: 'Naturally aromatic long grain rice',
    price: '$5.00',
    category: 'Biryani & Rice',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'br5',
    name: 'Saffron Basmati Rice',
    description: 'Naturally aromatic long grain rice',
    price: '$6.00',
    category: 'Biryani & Rice',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'br6',
    name: 'Shrimp Biryani',
    description: 'Aromatic basmati rice cooked with shrimp. Served with raita',
    price: '$27.00',
    category: 'Biryani & Rice',
    isGlutenFree: true,
  },
  {
    id: 'br7',
    name: 'Vegetable Biryani',
    description: 'Aromatic basmati rice cooked with vegetables, herbs, and spices. (Served with raita)',
    price: '$23.00',
    category: 'Biryani & Rice',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'br8',
    name: 'Hyderabadi Chicken Dum Biryani',
    description: 'Fragrant basmati rice, tender chicken, and aromatic spices, slow-cooked in a sealed pot (dum) for rich, flavorful bites.',
    price: '$25.00',
    category: 'Biryani & Rice',
    isGlutenFree: true,
    isChefSpecial: true,
  },

  // --- Breads ---
  {
    id: 'bread1',
    name: 'Garlic Naan',
    description: 'Bread made of white flour topped with fresh minced garlic',
    price: '$6.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread2',
    name: 'Butter Naan',
    description: 'Crispy white flour bread',
    price: '$5.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread3',
    name: 'Plain Naan',
    description: 'Crispy white flour bread',
    price: '$5.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread4',
    name: 'Jalwa Bread Basket',
    description: 'An assortment of naan, garlic naan, onion kulcha, and tandoori roti',
    price: '$15.00',
    category: 'Breads',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'bread5',
    name: 'Chili Garlic Naan',
    description: 'Bread made of white flour topped with fresh minced garlic and Indian green chili',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread6',
    name: 'Goat Cheese Naan',
    description: 'White flour bread stuffed with fresh goat cheese',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread7',
    name: 'Jalwa Paratha',
    description: 'A specialty of the house consisting of minced garlic and onion topped with fresh mint',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
    isChefSpecial: true,
  },
  {
    id: 'bread8',
    name: 'Peshwari Naan',
    description: 'A flour bread stuffed with raisin and cherry',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread9',
    name: 'Onion Kulcha',
    description: 'Bread made of white flour stuffed with fresh onion',
    price: '$6.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread10',
    name: 'Lacha Paratha',
    description: 'Multilayered whole wheat bread',
    price: '$6.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread11',
    name: 'Tandoori Roti',
    description: 'An unleavened whole wheat bread',
    price: '$5.00',
    category: 'Breads',
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'bread12',
    name: 'Garlic Rosemary Naan',
    description: 'White flour bread garnished with fresh rosemary and minced garlic',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread13',
    name: 'Jalebi Paratha',
    description: 'Multilayered flour bread',
    price: '$6.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread14',
    name: 'Pudina Paratha',
    description: 'Minted whole wheat bread',
    price: '$6.00',
    category: 'Breads',
    isVegetarian: true,
  },
  {
    id: 'bread15',
    name: 'ALOO PARANTHA',
    description: 'BREAD MADE OF WHOLE WHEAT FLOUR STUFFED WITH POTATOES ONIONS AND CHILIES',
    price: '$7.00',
    category: 'Breads',
    isVegetarian: true,
  },

  // --- Sides ---
  {
    id: 'sd1',
    name: 'Raita',
    description: 'A cool yogurt sauce made with cucumber and roasted cumin garnished with fresh cilantro.',
    price: '$5.00',
    category: 'Sides',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'sd2',
    name: 'The Original Mango Chutney',
    description: 'Sweet and tangy mango preserve.',
    price: '$5.00',
    category: 'Sides',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'sd3',
    name: 'Achar',
    description: 'Traditional Indian mixed pickle.',
    price: '$3.00',
    category: 'Sides',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'sd4',
    name: 'Papad and Chutney',
    description: 'Crispy lentil wafers served with chutney.',
    price: '$4.00',
    category: 'Sides',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'sd5',
    name: 'The Jalwa Mango Chutney',
    description: 'A sweet and tangy relish made with ripe mangoes, vinegar, sugar, and spices',
    price: '$7.00',
    category: 'Sides',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isChefSpecial: true,
  },

  // --- Desserts ---
  {
    id: 'd1',
    name: 'Shakori Rasmalai',
    description: 'Sweet, spongy, cottage cheese dumpling, flavored with green cardamom',
    price: '$7.00',
    category: 'Desserts',
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: 'd2',
    name: 'Gulab Jamun',
    description: 'A light warm pastry made from milk and soaked in honey',
    price: '$7.00',
    category: 'Desserts',
    isVegetarian: true,
  },
  {
    id: 'd3',
    name: 'Paan Masala Ice Cream',
    description: 'A chef special- mouth refreshing ice cream with Indian flavors',
    price: '$8.00',
    category: 'Desserts',
    isVegetarian: true,
    isChefSpecial: true,
    isGlutenFree: true,
  },
  {
    id: 'd4',
    name: 'Malai Kulfi Ice Cream',
    description: 'Traditional dense Indian ice cream flavored with cardamom and nuts.',
    price: '$7.00',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'd5',
    name: 'Moong Dal Halwa',
    description: 'Lentil pudding with clarified butter, milk, saffron, and cardamom',
    price: '$7.00',
    category: 'Desserts',
    isVegetarian: true,
    isGlutenFree: true,
  },

  // --- Beverages ---
  {
    id: 'bev1',
    name: 'Mango Lassi',
    description: 'A smooth and refreshing blend of ripe mangoes and creamy yogurt, lightly sweetened and served chilled.',
    price: '$5.00',
    category: 'Beverages',
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'bev2',
    name: 'Diet Coke',
    description: 'A crisp, refreshing taste you know and love with zero calories',
    price: '$3.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev3',
    name: 'Pellegrino Water',
    description: 'Sparkling mineral water',
    price: '$7.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev4',
    name: 'Still Water',
    description: 'Natural spring water',
    price: '$7.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev5',
    name: 'Club Soda',
    description: 'Refreshing carbonated water',
    price: '$3.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev6',
    name: 'Sprite',
    description: 'The cold, refreshing flavors of lemon and lime, perfectly blended',
    price: '$3.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev7',
    name: 'Coke',
    description: 'The cold, refreshing, sparkling classic that America loves',
    price: '$3.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: 'bev8',
    name: 'Ginger Ale',
    description: 'Crisp and refreshing ginger taste',
    price: '$3.00',
    category: 'Beverages',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    text: "The food was absolutely delicious. The vibe was cozy and warm, making it the perfect place to relax and enjoy a meal with friends. I especially loved the Chat – it was bursting with flavor!",
    author: "Priyank R.",
    source: "Google Reviews"
  },
  {
    id: 't2',
    text: "Just returned from vacation, and didn't want to cook so I decided to try JALWA. I ordered over the phone on my way home from work. I was pleasantly surprised by the staff’s friendliness...",
    author: "Alice W.",
    source: "Yelp"
  },
  {
    id: 't3',
    text: "Their food and catering is constantly delicious, we have been ordering and eating in here for close to 1.5 years. Their flavors are closest to Delhi. Love their Dal Bukhara, Pandara Road...",
    author: "Rewan R.",
    source: "Google Reviews"
  }
];

export const CONTACT_INFO = {
  address: "215 Glenridge Ave, Montclair, NJ 07042",
  phone: "(973) 250-6364",
  email: "info@jalwanj.com",
  reservationUrl: "https://www.opentable.com/restaurant/profile/1423882",
  hours: [
    "Mon: Closed",
    "Tue - Thu: 11:30 AM – 3:00 PM, 5:00 PM – 9:30 PM",
    "Fri - Sat: 11:30 AM – 3:00 PM, 5:00 PM – 10:00 PM",
    "Sun: 12:00 PM – 3:00 PM, 5:00 PM – 9:30 PM"
  ],
  socials: {
    instagram: "https://www.instagram.com/jalwa_montclair/",
    facebook: "https://www.facebook.com/JalwaModernIndianDining/",
    x: "https://x.com/JalwaMontclair",
    tiktok: "https://www.tiktok.com/@jalwamontclair"
  }
};

export const PARTY_TRAY_ITEMS = [
  {
    category: 'Vegetarian Appetizers',
    items: [
      { name: 'Samosa (Cocktail)', half: '$40', full: '$75' },
      { name: 'Lasooni Gobi', half: '$55', full: '$100' },
      { name: 'Hara Bhara Kabab', half: '$50', full: '$95' },
      { name: 'Paneer Tikka', half: '$60', full: '$115' },
      { name: 'Chilli Paneer', half: '$60', full: '$115' },
      { name: 'Vegetable Manchurian', half: '$55', full: '$100' },
      { name: 'Gobi Manchurian', half: '$55', full: '$100' },
    ]
  },
  {
    category: 'Non-Veg Appetizers',
    items: [
      { name: 'Chicken 65', half: '$65', full: '$125' },
      { name: 'Chicken Tikka', half: '$65', full: '$125' },
      { name: 'Chilli Chicken', half: '$65', full: '$125' },
      { name: 'Seekh Kabab (Lamb)', half: '$75', full: '$145' },
      { name: 'Fish Amritsari', half: '$70', full: '$135' },
      { name: 'Chicken Malai Kabab', half: '$65', full: '$125' },
    ]
  },
  {
    category: 'Vegetarian Curries',
    items: [
      { name: 'Dal Makhani', half: '$50', full: '$95' },
      { name: 'Paneer Tikka Masala', half: '$60', full: '$115' },
      { name: 'Saag Paneer', half: '$60', full: '$115' },
      { name: 'Malai Kofta', half: '$60', full: '$115' },
      { name: 'Chana Masala', half: '$50', full: '$95' },
      { name: 'Aloo Gobi', half: '$50', full: '$95' },
      { name: 'Mixed Vegetable Curry', half: '$50', full: '$95' },
    ]
  },
  {
    category: 'Chicken Curries',
    items: [
      { name: 'Butter Chicken', half: '$65', full: '$125' },
      { name: 'Chicken Tikka Masala', half: '$65', full: '$125' },
      { name: 'Chicken Curry (Home Style)', half: '$60', full: '$115' },
      { name: 'Chicken Korma', half: '$65', full: '$125' },
      { name: 'Chicken Vindaloo', half: '$60', full: '$115' },
      { name: 'Chicken Saag', half: '$60', full: '$115' },
      { name: 'Chicken Kadai', half: '$60', full: '$115' },
    ]
  },
  {
    category: 'Lamb & Goat',
    items: [
      { name: 'Lamb Rogan Josh', half: '$75', full: '$145' },
      { name: 'Lamb Vindaloo', half: '$75', full: '$145' },
      { name: 'Lamb Curry', half: '$75', full: '$145' },
      { name: 'Goat Curry', half: '$75', full: '$145' },
      { name: 'Goat Korma', half: '$75', full: '$145' },
    ]
  },
  {
    category: 'Seafood',
    items: [
      { name: 'Goan Fish Curry', half: '$70', full: '$135' },
      { name: 'Shrimp Masala', half: '$75', full: '$145' },
      { name: 'Shrimp Vindaloo', half: '$75', full: '$145' },
    ]
  },
  {
    category: 'Biryani & Rice',
    items: [
      { name: 'Vegetable Biryani', half: '$50', full: '$95' },
      { name: 'Chicken Biryani', half: '$60', full: '$115' },
      { name: 'Lamb Biryani', half: '$70', full: '$135' },
      { name: 'Goat Biryani', half: '$70', full: '$135' },
      { name: 'Jeera Rice', half: '$25', full: '$45' },
      { name: 'Peas Pulao', half: '$30', full: '$55' },
    ]
  },
  {
    category: 'Breads & Sides',
    items: [
      { name: 'Naan (Plain)', half: '$25', full: '$45' },
      { name: 'Naan (Garlic)', half: '$30', full: '$55' },
      { name: 'Tandoori Roti', half: '$25', full: '$45' },
      { name: 'Raita', half: '$20', full: '$35' },
      { name: 'Garden Salad', half: '$25', full: '$45' },
    ]
  },
  {
    category: 'Desserts',
    items: [
      { name: 'Gulab Jamun', half: '$40', full: '$75' },
      { name: 'Rasmalai', half: '$50', full: '$95' },
      { name: 'Rice Kheer', half: '$40', full: '$75' },
      { name: 'Gajar Halwa', half: '$45', full: '$85' },
    ]
  }
];
